name: Build APK

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Website URL"
        required: true
      app_name:
        description: "App Name"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Android
      uses: android-actions/setup-android@v3

    - name: Install ImageMagick
      run: sudo apt-get install -y imagemagick

    - name: Set App Name
      run: |
        sed -i "s|MY_APP_NAME|${{ github.event.inputs.app_name }}|g" template/app/src/main/res/values/strings.xml

    - name: Download Logo
      run: |
        curl -L "https://www.google.com/s2/favicons?sz=512&domain=${{ github.event.inputs.site }}" -o logo.png
        
    - name: Generate All Icons
      run: |
        mkdir -p icons

        convert logo.png -resize 48x48 icons/mdpi.webp
        convert logo.png -resize 72x72 icons/hdpi.webp
        convert logo.png -resize 96x96 icons/xhdpi.webp
        convert logo.png -resize 144x144 icons/xxhdpi.webp
        convert logo.png -resize 192x192 icons/xxxhdpi.webp

        # Square icon (launcher)
        convert logo.png -resize 512x512 -background white -gravity center -extent 512x512 icons/ic_launcher.webp

        # Round icon (launcher)
        convert logo.png -resize 512x512 -gravity center -extent 512x512 icons/ic_launcher_round.webp

    - name: Replace Icons
      run: |
        cp icons/mdpi.webp template/app/src/main/res/mipmap-mdpi/ic_launcher.webp
        cp icons/hdpi.webp template/app/src/main/res/mipmap-hdpi/ic_launcher.webp
        cp icons/xhdpi.webp template/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
        cp icons/xxhdpi.webp template/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
        cp icons/xxxhdpi.webp template/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp

        cp icons/ic_launcher.webp template/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
        cp icons/ic_launcher_round.webp template/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
        cp icons/ic_launcher_round.webp template/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
        cp icons/ic_launcher_round.webp template/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
        cp icons/ic_launcher_round.webp template/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp

    - name: Replace URL
      run: |
        sed -i "s|MY_URL|${{ github.event.inputs.url }}|g" template/app/src/main/java/com/webviewtemplate/webviewtemplate/MainActivity.kt

    - name: Build APK
      run: |
        cd template
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: template/app/build/outputs/apk/debug/app-debug.apk
